---

- name: Configure the ssh service
  hosts: machines:!vms
  become: true
  vars:
    ansible_ssh_user: "{{ original_credentials['user'] }}"
    ansible_ssh_pass: "{{ original_credentials['pass'] }}"
    ansible_become_pass: "{{ original_credentials['pass'] }}"
  tasks:
    - name: Upload pub key for root user
      ansible.posix.authorized_key:
        user: root
        key: "{{ lookup('file', '~/.ssh/aise-dsu.pub') }}"

    - name: Check root ssh works
      wait_for_connection: ~
      vars:
        ansible_ssh_user: root

- name: Install python
  hosts: machines
  tags: install-pip
  tasks:
    - name: Install pip
      apt:
        name: python3-pip
        update_cache: true
