---

- name: Run the server(s)
  hosts: servers
  tasks:
    - name: Run the docker image for the server
      systemd:
        name: flwr-model@server
        daemon_reload: true
        state: restarted
      environment:
        flmodel_role: server

- name: Run the clients
  hosts: docker_clients
  gather_facts: false
  tasks:
    - name: Check the server is up
      wait_for:
        host: "{{ hostvars[server]['ansible_host'] }}"
        port: 8080
        timeout: 10
      loop: "{{ groups['servers'] }}"
      loop_control:
        loop_var: server
      delegate_to: localhost

    - name: Run the docker image for the clients
      systemd:
        name: "flwr-model@{{ inventory_hostname }}"
        daemon_reload: true
        state: restarted
      environment:
        flmodel_role: client
      delegate_to: "{{ docker_server }}"
