---

- name: Delete any files we have uploaded  # apt/pip packages will be left behind
  hosts: servers, client_machines
  become: true
  tags: never
  tasks:
    - name: Delete workspace folder
      file:
        path: "{{ workspace_dir }}"
        state: absent
